other
backofficePortalCss

^'/* START: BACK OFFICE STYLES */
#add-new-import-form {
  display: inline-flex;
  margin-top: 10px;
}
#add-new-form-button {
  padding: 10px;
}
#add-rol-button {
  float: left;
  margin-top: 20px;
}
#add-user-button {
  float: left;
  margin-top: 40px;
}
#applications-list {
  float: left;
  margin-left: 10px;
}
#applications-list select {
  width: 300px;
}
#bpm-report-graph {
	height: 1000px;
	width: 1500px;
	display: contents;
}
#bpm-report-bottom-options form {
	border-radius: 10px;
	background-color: darkgray;
	margin: 10px;
	width: 250px;
	border-style: inset;
	border-width: 1px;
}
#bpm-report-bottom-options form fieldset {
	border: 0;
}
#environment-applications {
	width: 55%;
	display: inline-block;
    padding-top: 5px;
}
#environment-users {
	width: 45%;
	display: inline-block;
}
#environment-applications-title {
	font-size: 25px;
	padding-left: 20px;
	padding-top: 10px;
}
#environment-svg {
	height: 60px
}
#environment-users-title {
	font-size: 25px;
	padding-left: 10px;
	padding-top: 10px;
}
#environment-users-table {
}
#forms-operations {
  float: left;
  width: 200px;
}
#forms-operations input {
  border-radius: 10px;
  margin-left: 10px;
  margin-bottom: 10px;
}
#immutable-import-exception {
	padding: 10px;
	margin: 10px;
	text-align: center;
	background-color: beige;
	border-radius: 15px;
	display: grid;
}
#immutable-import-exception strong {
	color: red;
}
#immutable-import-exception output {
	margin: 5px;
}
.import-all-button-1 {
  padding: 10px;
}
.import-all-button-2 {
  margin-top: 10px;
  margin-left: 10px;
}
.import-csv-info {
  background-color: beige;
  padding: 10px;
  border-radius: 15px;
  border: 2px solid green;
	max-width: 250px;
}
#import-forms {
  overflow-y: auto;
  display: inline-block;
  width: 100%;
  bottom: 0px;
  max-height: 100%;
  top: 112px;
  margin-top: 10px;
}
#import-reset {
	float: left;
	padding-left: 5px;
}
#imported-processes {
	display: inline-flex;
}
#imported-processes-sucessful {
	font-size: 25px;
	background-color: beige;
	border-radius: 10px;
	padding: 10px;
	margin: 10px;
	color: darkgreen;
	text-align: center;
}
#imported-processes-title {
	margin-left: 15px;
	margin-top: 15px;
	font-size: 20px;
	font-style: italic;
}
#imported-processes-confirmation {
	margin-top: 65px;
}
#imported-processes-failed {
	font-size: 25px;
	background-color: beige;
	border-radius: 10px;
	padding: 10px;
	margin: 10px;
	color: red;
	text-align: center;
}
#imported-processes-failed span output {
	font-size: 18px;
	padding: 10px;
	margin: 10px;
	color: black;
	text-align: center;
	display: block;
}
.imported-process {
	border-radius: 10px;
	background: gray;
	padding-top: 20px;
	padding-left: 10px;
	padding-right: 10px;
	padding-bottom: 10px;
	margin: 15px;
}
.information-xpdl-import {
	background-color: #898a8a;
	border-radius: 10px;
	padding: 15px;
	margin-top: 20px;
	margin-left: 10px;
	margin-right: 10px;
}
.information-xpdl-import  div {
	font-size: 20px;
}
.information-xpdl-import output strong {
	font-size: 20px;
}
.information-xpdl-import span {
	display: inherit;
}
.information-xpdl-import span strong {
	font-style: italic;
	color: white;
}
#internationalization {
}
#internationalization fieldset {
  border: medium none;
}
#internationalization label, #internationalization input, #internationalization select {
  width: 200px;
  border-radius: 10px;
  margin-right: 15px;
}
#internationalization-switch {
	margin: 5px;
}

#inter-current-dictionary {
  height: 480px;
  margin-left: auto;
  margin-right: auto;
  width: 90%;
  overflow-y: auto;
}
#inter-current-dictionary output {
  color: #66650B;
}
#inter-current-dictionary span {
  color: rgb(14, 79, 101);
}
#orbeon-definitions-list {
  padding-top: 10px;
  float: left;
}
#orbeon-list-application {
  padding-top: 20px;
  float: left;
}
#radar {
  display: inline-flex;
}
#remove-new-form-button {
  padding-top: 10px;
}
#rols-users {
  padding-bottom: 20px;
}
#rols-and-users {
  float: left;
  display: inline-flex;
}
#system-rols {
  display: inline-flex;
  float: left;
}
#system-users {
  display: inline-flex;
  float: left;
}
#users-and-rols {
  float: left;  
}
#users-configuration {
}
#user-rols {
}
#users-to-add-to-role {
  float: left;
}
#users-to-add-to-role input {
  border-radius: 10px;
}
#users-to-add-to-role input[type="submit"] {
  margin-top: 20px;
}
/* END: BACK OFFICE STYLES */
'