other
orbeonPortalCss

^'
#content {
	height: 100%;
}
#export-component {
	margin-top: 10px;
}
#export-component input[type="submit"] {
  border-radius: 5px;
}
#form-instances-component {
	display: inline-flex;
	margin-top: 5px;
	margin-left: 5px;
}
.query-block-error {
    color: red;
    margin: 15px;
    font-size: 150%;
    border-style: groove;
    padding: 10px;
    text-align: center;
}
#orbeon-graph {
	display: inline-block;
	margin-top: 15px;
	width: 1600px;
	height: 470px;
	overflow: scroll;
}
.radio-button-container {
	border-style: inset;
	border-width: 1px;
	margin-bottom: 10px;
	border-color: gainsboro;
	padding-top: 10px;
}
.radio-button-horizontal {
	display: inline-flex !important;
	margin-right: 5px;
}
.selected-field-list {
	border-style: inset;
	border-width: 1px;
	border-color: gainsboro;
	margin-bottom: 10px;
	font-weight: bold;
}
'