other
orbeonPortalCss

^'
#content {
	height: 100%;
}
#chart-form {
	height: 250px;
	overflow: auto;	
}
#export-component {
	margin-top: 10px;
}
#export-component input[type="submit"] {
  border-radius: 5px;
}
#form-instances-component {
	display: inline-flex;
	margin-top: 5px;
	margin-left: 5px;
}
.query-block-error {
    color: red;
    margin: 15px;
    font-size: 150%;
    border-style: groove;
    padding: 10px;
    text-align: center;
}
#orbeon-graph {
	display: inline-block;
	margin-top: 15px;
	width: 1600px;
	height: 470px;
	overflow: scroll;
}
.radio-button-container {
	border-width: 1px;
	margin-bottom: 10px;
	border-color: gainsboro;
	padding-top: 10px;
}
.radio-button-container fieldset {
	display: grid;
}
.radio-button-horizontal {
	display: inline-flex !important;
	margin-right: 5px;
}
.selected-field-list {
	border-width: 1px;
	border-color: gainsboro;
	margin-bottom: 10px;
	font-weight: bold;
}
#sewaf-wizard {
	height: 100%;
}
#sewaf-wizard-component {
	height: 80%;
}
#sewaf-wizard-navigation {
	height: 25px;
	margin-top: 20px;
}
'