other
style

	^'
h1 {margin-left: 35px;}
body {
	margin-bottom: 25px !important;
	background-color: darkgrey;
}
#flags {
	float: right;
}
#flags img {
	margin-right: 5px;
}
.flag {
	float: left;
}
.flag-last {
	margin-right: 10px;
}
#login {
	border-radius: 25px;
	padding-top: 20px;
	padding-bottom: 20px;
    width: 380px; 
    margin: 0 auto;
	background-color: lightblue;
}
#login form{
    width:50%;
	background-color: lightblue;
	margin-left: 35px;
}
#login form p {
	color: darkred;
}
#user-div {
	margin-bottom: 5px;
	display: inline-block;
	width: 80%;
}
#user-div input {
	border-radius: 15px;
	width: 200px;
	display: block;
}
#user-div label {
	display: block;
}
#password-div {
	display: inline-block;
	width: 80%;
}
#password-div label {
	display: block;
}
#password-div input {
	border-radius: 15px;
	display: block;
	width: 200px;
}
#login-button {
	display: block;
	margin-top: 10px;
}
#login-button input {
	border-radius: 8px;
}'